name: Auto Update
on:
  schedule:
    - cron: '*/1 3-5 * * 1-5'  # 9:30 AM - 12:01 PM (MMT)
    - cron: '*/1 7-10 * * 1-5' # 2:00 PM - 4:30 PM (MMT)
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install axios firebase-admin
      - run: node worker.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
